services:
  Richardhj\ContaoGitlabTriggerBundle\GitlabPipelineTrigger: 
    arguments:
      ['@?gitlab_api']

  Richardhj\ContaoGitlabTriggerBundle\EventListener\DataContainer\TriggerGitlabPipelineCommand:
    arguments: ['@Richardhj\ContaoGitlabTriggerBundle\GitlabPipelineTrigger','@router']
    public: true

  Richardhj\ContaoGitlabTriggerBundle\EventListener\DataContainer\PipelineLogLabelCallback:
    public: true
    arguments:
      ['@?gitlab_api']

  Richardhj\ContaoGitlabTriggerBundle\ContaoTrigger\Action\TriggerGitlabPipelineAction:
    arguments: ['@Richardhj\ContaoGitlabTriggerBundle\GitlabPipelineTrigger']
    tags:
      - { name: eblick_contao_trigger.action, alias: gitlab_pipeline }
