services:
  ErdmannFreunde\ContaoGitlabTriggerBundle\GitlabPipelineTrigger: 
    arguments:
      ['@?gitlab_api']

  ErdmannFreunde\ContaoGitlabTriggerBundle\EventListener\DataContainer\TriggerGitlabPipelineCommand:
    arguments: ['@ErdmannFreunde\ContaoGitlabTriggerBundle\GitlabPipelineTrigger','@router']
    public: true

  ErdmannFreunde\ContaoGitlabTriggerBundle\EventListener\DataContainer\PipelineLogLabelCallback:
    public: true
    arguments:
      ['@?gitlab_api']

  ErdmannFreunde\ContaoGitlabTriggerBundle\ContaoTrigger\Action\TriggerGitlabPipelineAction:
    arguments: ['@ErdmannFreunde\ContaoGitlabTriggerBundle\GitlabPipelineTrigger']
    tags:
      - { name: eblick_contao_trigger.action, alias: gitlab_pipeline }
